### ISSUE TITLE
Request FaceID if button pressed

### ISSUE THREAD

**Issue by Aem2512** [MTACS/FingerLock#7]
This is not a bug. This is a request feature. It would be so usefull for faceID devices if button requests faceID than requesting passcode if device still unlocked. (Like scanning your face after you swiped up on lockscreen)

**Comment by MTACS** [comment]
Good idea, I'll see if I can get it added

**Comment by MTACS** [comment]
Got it working, it'll be included in the next version

**Comment by Aem2512** [comment]
Thanks! 😁
